### ISSUE TITLE
New screenshots needed

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-amazon-web-services#17]
Everything is the same but different! We need to add updated screenshots so that our tutorial reflects the current look of AWS. 
Related to #167

**Comment by finnhodgkin** [comment]
@nelsonic What are you using for the nice drop-shadowed screenshots? I could hop into Photoshop and manually edit each image to match the current ones, but if there's a tool..?

**Comment by finnhodgkin** [comment]
Hmm having Googled it appears to be an OSX thing. 
I'll look for a linux option now.

**Comment by nelsonic** [comment]
@finnhodgkin for screenshots I'm just using standard ***mac*** keyboard shortcut. https://www.take-a-screenshot.org/
I don't know if there _is_ a way to get the "window" screnshot on Ubuntu with the "_shadow_" but equally, I don't think this is an issue as what matters is the content of the screenshot.

The only thing I will note is: Minimise the window (_pixel_) dimensions for your screenshots and
avoid including any "noise" in them e.g: don't take a screenshot that includes lots of other tabs or "browser chrome".

Also Please note: https://github.com/dwyl/learn-amazon-web-services/issues/24

**Comment by finnhodgkin** [comment]
I'm retaking the screenshots now. :+1: 

Shutter (linux app) seems to emulate the Mac look pretty well. The content of the screenshot is for sure more important but it's still nice to have prettier things.

**Comment by finnhodgkin** [comment]
Taking a little longer than 25m because I'm going through the S3 stuff too (thought the current screenshots were ok but actually they're a bit different :cry: )

**Comment by finnhodgkin** [comment]
Finished collecting the images. Adding them all to the readme now.

**Comment by finnhodgkin** [comment]
We've replaced all screenshots with nice up to date versions.
Can close this and #24 :+1:
