### ISSUE TITLE
Change "tweet me" to "raise an issue"

### ISSUE THREAD

**Issue by ZooeyMiller** [dwyl/learn-amazon-web-services#25]
In the readme at the moment there is (on line 17+18) this: 
> As always, if you have any questions, tweet me! [@nelsonic](https://twitter.com/nelsonic)

I'd like to change this to 
> As always, if you have questions, [raise an issue](https://github.com/dwyl/learn-amazon-web-services/issues/new)! :sparkles: 

I feel the change shows dwyl as more of a community and acknowledges the collaborative nature of our open source repos. 

Assigned as I would like confirmation of it being okay before adding this to a PR

**Comment by nelsonic** [comment]
good suggestion. please update. 👍  (_thanks!_)

**Comment by ZooeyMiller** [comment]
done in a9c7cba. Issue will be closed when `confirmed-readme-updates` is merged into master.
